[build]
  command = "npm run build"
  publish = "dist"

# Allow Firebase environment variables in build output
# Firebase API keys are designed to be public and are secured via Firebase Security Rules
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_FIREBASE_API_KEY,VITE_FIREBASE_APP_ID,VITE_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_MESSAGING_SENDER_ID,VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_STORAGE_BUCKET"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
